version: '2'
services:
  postgresql:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: 'saveallthethings'
      POSTGRES_USER: 'arq-soft'

  app:
    build: .
    stdin_open: true
    ports:
      - "9000:9000"
    environment:
      JDBC_DATABASE_URL: 'jdbc:postgresql://postgresql:5432/arq-soft?user=arq-soft&password=saveallthethings'
    depends_on:
      - postgresql
